// ============================================================
// js/ebay.js — eBay search link builder + EPN affiliate tracking
//
// Affiliate params from BOBA-Scanner EPN account:
//   campid  : 5339143193  (Campaign: "default")
//   mkrid   : 711-53200-19255-0  (US rotation ID)
//   siteid  : 0  (eBay US)
//   toolid  : 10001
//   mkevt   : 1
//   mkcid   : 1
//
// Every eBay URL generated by this module automatically appends
// these params so affiliate commission is tracked on any resulting
// purchase.
// ============================================================

const EBAY_AFFILIATE = {
  campid:  '5339143193',
  mkrid:   '711-53200-19255-0',
  siteid:  '0',
  toolid:  '10001',
  mkevt:   '1',
  mkcid:   '1'
};

const EBAY_SEARCH_BASE = 'https://www.ebay.com/sch/i.html';

// ── Build search query from card metadata ─────────────────────────────────────
// Strategy: most specific first — card number narrows results dramatically.
// We always include "bo jackson" to keep results on target.
// Parallel and weapon are included when non-trivial (skip "Base", "None", etc.)

function buildEbayQuery(card) {
  const parts = [];

  // Year — helps disambiguate across set releases
  if (card.year) parts.push(card.year.trim());

  // Always anchor to Bo Jackson
  parts.push('bo jackson');

  // Card number — single most important identifier
  if (card.cardNumber) parts.push(card.cardNumber.trim());

  // Set name — cleaned up
  if (card.set) {
    const set = card.set.trim();
    if (set && set.toLowerCase() !== 'unknown') parts.push(set);
  }

  // Parallel — skip generic/blank values
  if (card.pose) {
    const pose = card.pose.trim().toLowerCase();
    if (pose && pose !== 'base' && pose !== 'base card' && pose !== 'none' && pose !== 'unknown' && pose !== '-') {
      parts.push(card.pose.trim());
    }
  }

  // Weapon — skip "None" / blank
  if (card.weapon) {
    const weapon = card.weapon.trim().toLowerCase();
    if (weapon && weapon !== 'none' && weapon !== 'unknown' && weapon !== 'n/a' && weapon !== '-') {
      parts.push(card.weapon.trim());
    }
  }

  return parts.join(' ');
}

// ── Append EPN affiliate params ───────────────────────────────────────────────
function appendAffiliateParams(url) {
  const separator = url.includes('?') ? '&' : '?';
  const params = new URLSearchParams(EBAY_AFFILIATE).toString();
  return `${url}${separator}${params}`;
}

// ── Build complete eBay search URL ────────────────────────────────────────────
function buildEbaySearchUrl(card) {
  const query = buildEbayQuery(card);
  if (!query.trim()) return null;

  const searchUrl = `${EBAY_SEARCH_BASE}?_nkw=${encodeURIComponent(query)}&_sacat=0&LH_TitleDesc=0`;
  return appendAffiliateParams(searchUrl);
}

// ── Open eBay search in new tab ───────────────────────────────────────────────
window.openEbaySearch = function(cardIndex) {
  const collections = getCollections();
  const currentId   = getCurrentCollectionId();
  const collection  = collections.find(c => c.id === currentId);

  if (!collection?.cards[cardIndex]) {
    showToast('Card not found', '❌');
    return;
  }

  const card = collection.cards[cardIndex];
  const url  = buildEbaySearchUrl(card);

  if (!url) {
    showToast('Not enough card info to search eBay', '⚠️');
    return;
  }

  window.open(url, '_blank', 'noopener,noreferrer');
};

// ── Expose for use in collection modal (tags.js) ──────────────────────────────
window.buildEbaySearchUrl = buildEbaySearchUrl;
window.buildEbayQuery     = buildEbayQuery;

console.log('✅ eBay module loaded');
