// ============================================================
// js/ebay.js — eBay search link builder + EPN affiliate tracking
//
// Affiliate params from BOBA-Scanner EPN account:
//   campid  : 5339143193  (Campaign: "default")
//   mkrid   : 711-53200-19255-0  (US rotation ID)
//   siteid  : 0  (eBay US)
//   toolid  : 10001
//   mkevt   : 1
//   mkcid   : 1
//
// Every eBay URL generated by this module automatically appends
// these params so affiliate commission is tracked on any resulting
// purchase.
// ============================================================

const EBAY_AFFILIATE = {
  campid:  '5339143193',
  mkrid:   '711-53200-19255-0',
  siteid:  '0',
  toolid:  '10001',
  mkevt:   '1',
  mkcid:   '1'
};

const EBAY_SEARCH_BASE = 'https://www.ebay.com/sch/i.html';

// ── Build search query from card metadata ─────────────────────────────────────
// Strategy: most specific first — card number narrows results dramatically.
// We always include "bo jackson" to keep results on target.
// Parallel and weapon are included when non-trivial (skip "Base", "None", etc.)

function buildEbayQuery(card) {
  // Helper: safely coerce any value to trimmed string
  const s = v => String(v ?? '').trim();

  const parts = [];

  // "bo jackson battle arena" — anchors to the game, not just the player
  parts.push('bo jackson battle arena');

  // Card number — most specific identifier (e.g. BLBF-84)
  const cardNum = s(card.cardNumber);
  if (cardNum) parts.push(cardNum);

  // Hero name — helps narrow parallel variants
  const hero = s(card.hero);
  if (hero && hero.toLowerCase() !== 'unknown') parts.push(hero);

  // Intentionally excluded:
  //   set name  (Alpha Update, Battle Arena, etc) — too verbose, hurts results
  //   parallel  (Blizzard Battlefoil Glow, etc)   — most sellers don't include this
  //   weapon    — rarely in listing titles
  //   year      — card number already disambiguates

  return parts.join(' ');
}

// ── Append EPN affiliate params ───────────────────────────────────────────────
function appendAffiliateParams(url) {
  const separator = url.includes('?') ? '&' : '?';
  const params = new URLSearchParams(EBAY_AFFILIATE).toString();
  return `${url}${separator}${params}`;
}

// ── Build complete eBay search URL ────────────────────────────────────────────
function buildEbaySearchUrl(card) {
  const query = buildEbayQuery(card);
  if (!query.trim()) return null;

  const searchUrl = `${EBAY_SEARCH_BASE}?_nkw=${encodeURIComponent(query)}&_sacat=0&LH_TitleDesc=0`;
  return appendAffiliateParams(searchUrl);
}

// ── Open eBay search in new tab ───────────────────────────────────────────────
window.openEbaySearch = function(cardIndex) {
  const collections = getCollections();
  const currentId   = getCurrentCollectionId();
  const collection  = collections.find(c => c.id === currentId);

  if (!collection?.cards[cardIndex]) {
    showToast('Card not found', '❌');
    return;
  }

  const card = collection.cards[cardIndex];
  const url  = buildEbaySearchUrl(card);

  if (!url) {
    showToast('Not enough card info to search eBay', '⚠️');
    return;
  }

  window.open(url, '_blank', 'noopener,noreferrer');
};

// ── Expose for use in collection modal (tags.js) ──────────────────────────────
window.buildEbaySearchUrl = buildEbaySearchUrl;
window.buildEbayQuery     = buildEbayQuery;

console.log('✅ eBay module loaded');
