// js/heroes.js
// Lookup table: Bo Jackson Battle Arena hero name → real-life athlete inspiration.
// Keys are uppercased for case-insensitive matching.
// Multiple heroes can map to the same athlete (e.g. Freakshow → Giannis).
// Used by scanner.js to auto-populate card.athlete on every scan.

const HERO_TO_ATHLETE = {
  'BRAUN':              'A.J. Brown',
  'AJAX':               "A'ja Wilson",
  'GAVELER':            'Aaron Judge',
  'DOUBLECHECK':        'Aaron Rodgers',
  'AIR ACE':            'Ace Bailey',
  'CRUSCHMAN':          'Adley Rutschman',
  'BRAWN':              'AJ Brown',
  'SARRTILLERY':        'Alexandre Sarr',
  'A.I.':               'Allen Iverson',
  'CAMERA':             'Alvin Kamara',
  'AMON-RA':            'Amon-Ra St. Brown',
  'AWESOME DAWSON':     'Andre Dawson',
  'CLUTCH':             'Andrew McCutchen',
  'CURAÇAO KID':        'Anduw Jones',
  'SIMON SAYS':         'Anfernee Simons',
  'HALO':               'Angel Reese',
  'UNIBROW':            'Anthony Davis',
  'ANT HILL':           'Anthony Edwards',
  'JEANETIC':           'Ashton Jeanty',
  'BAMMER':             'Bam Adebayo',
  'BARRY "CUTBACK" SANDERS': 'Barry Sanders',
  'DIJON':              'Bijon Robinson',
  'BILLY':              'Billy the Pug',
  'BOJAX':              'Bo Jackson',
  'PHOENIX':            'Bo Nix',
  'GIGAWITT':           'Bobby Witt Jr.',
  'BOOM':               'Boomer Esiason',
  'BREEZE':             'Breece Hall',
  'ROOK':               'Brent Rooker',
  'BOZ':                'Brian Bosworth',
  'THOMSTONE':          'Brian Thomas Jr.',
  'BROCKNESS':          'Brock Bowers',
  'MR. IRRELEVANT':     'Brock Purdy',
  'HARPOON':            'Bryce Harper',
  'BUCKSHOT':           'Buck Showalter',
  'CICADA':             'Cade Cunningham',
  'C.C.':               'Caitlin Clark',
  'DUMPER':             'Cal Raleigh',
  'THE IRONMAN':        'Cal Ripken Jr.',
  'CALIBER':            'Caleb Williams',
  'CHILLER':            'Cam Thomas',
  'WARDEN':             'Cam Ward',
  'CAMELEON':           'Cameron Brink',
  'BIONIC':             'Carlos Correa',
  'SHEPHERD':           'CeeDee Lamb',
  'BRANDI':             'Brandi Chastain',
  'CHETMATE':           'Chet Holmgren',
  'BOSHPIT':            'Chris Bosh',
  'MCARMYKNIFE':        'Christian McCaffrey',
  'ALIEN':              'CJ Abrams',
  'CJ MADDUX':          'CJ Maddux',
  'SHROUDED':           'CJ Stroud',
  'AMOEBA':             'Collin Murray-Boyles',
  'DEGENIE':            'Cooper Dejean',
  'MAVERICK':           'Cooper Flagg',
  'BARRELER':           'Cooper Kupp',
  'CARROLLER':          'Corbin Carroll',
  'COWBOY':             'Corey Seager',
  'COURTHOUSE':         'Courtland Sutton',
  'COOPANOVA':          'Cynthia Cooper',
  'ATTAK':              'Dak Prescott',
  'TIME':               'Damian Lillard',
  'MARINO':             'Dan Marino',
  'LIEUTENANT':         'Dansby Swanson',
  'WOODY':              'Darren Woodson',
  'SMOKE':              'Dave Stewart',
  'FOXHOLE':            "De'Aaron Fox",
  'D-HOP':              'DeAndre Hopkins',
  'THORN':              'DeMar DeRozan',
  'TANK':               'Derrick Henry',
  'LIBRARIAN':          'Devin Booker',
  'DEVAULTA':           'DeVonta Smith',
  'DEKAP':              'DK Metcalf',
  'SABOTAGE':           'Domantas Sabonis',
  'WINDMILL':           'Dominique Wilkins',
  'DONNIE BASEBALL':    'Don Mattingly',
  'SPIDER':             'Donovan Mitchell',
  'FLUTIE':             'Doug Flutie',
  'BALDWING':           'Drake Baldwin',
  'DRACO':              'Drake Maye',
  'CREWS-MISSLE':       'Dylan Crews',
  'D-HARP':             'Dylan Harper',
  'STEADY EDDIE':       'Eddie George',
  'CRUZE-CONTROL':      'Elly De La Cruz',
  'BOMBEEZY':           'Emilio Estevez',
  'EMMITT-164':         'Emmitt Smith',
  'GOGGLES':            'Eric Dickerson',
  'PET DOG':            'Ethan Petry',
  'PET-DOG':            'Ethan Petry',
  'GO-CART':            'Evan Carter',
  'TATTOO':             'Fernando Tatís Jr.',
  'GRIN':               'Francisco Lindor',
  'TIKOFF':             'Fred Biletnikoff',
  'MVFREE':             'Freddie Freeman',
  'DEEP FREEZE':        'George Gervin',
  'FREAKSHOW':          'Giannis Antetokounmpo',
  'GUNNER':             'Gunnar Henderson',
  'HOWIETZER':          'Howie Long',
  'JAMBOX':             'Ja Morant',
  'BAYOU':              "Ja'Marr Chase",
  'JACHAMMER':          'Jac Caglianone',
  'CHA-CHING':          'Jackson Chourio',
  'ACTION':             'Jackson Holliday',
  'MERRI-GO-ROUND':     'Jackson Merrill',
  'HITSTICK':           'Jadeveon Clowney',
  'BURNER':             'Jalen Brunson',
  'GREEN-MACHINE':      'Jalen Green',
  'EAGLE-EYE':          'Jalen Hurts',
  'JAVALANCHE':         'Jamal Murray',
  'WILD BEARD':         'James Harden',
  'WILDBEARD':          'James Harden',
  'LUMBER':             'James Wood',
  'DART-BOARD':         'Jaxson Dart',
  'BONE':               'Jay Buhner',
  'JAYBIRD':            'Jayden Daniels',
  'JUICE':              'Jaylen Brown',
  'WADDLER':            'Jaylen Waddle',
  "TAZE'EM":            'Jayson Tatum',
  'ROCKSTAR':           'Jazz Chisholm',
  'BUS':                'Jerome Bettis',
  'KURSE':              'Jevon Kearse',
  'PALMER':             'Jim Palmer',
  'JEEVES':             'Jimmy Butler',
  "HOWBOUT'EM":         'Jimmy Johnson',
  'BURROCIOUS':         'Joe Burrow',
  'THIGHS MAN':         'Joe Theismann',
  'PROCESSOR':          'Joel Embiid',
  'JOEY JAWZ':          'Joey Chestnut',
  'BOTTO':              'Joey Votto',
  'BISON':              'Josh Allen',           // also John Allen — Josh Allen is primary
  'CAVEMAN':            'Johnny Damon',
  'STITCHER':           'Jonathan Taylor',
  'BOMBER':             'Yordan Alvarez',
  'CUPID':              'Jordan Love',
  'ESCAPE ARTIST':      'Jordan Spieth',
  'RAM':                'José Ramírez',
  'CHOSEN':             'Juan Soto',
  'LIGHTNINGROD':       'Julio Rodriguez',
  'ZEPHYR':             'Jung Hoo Lee',
  'J-CAM':              'Junior Caminero',
  'FORCEFIELD':         'Justin Fields',
  'BOLTAGE':            'Justin Herbert',
  'J-JETTS':            'Justin Jefferson',
  'KAT':                'Karl-Anthony Towns',
  'LEDUCKY':            'Katie Ledecky',
  'FUNGI':              'Kawhi Leonard',
  'CANINE':             'Kenneth Walker III',
  'KETTLE-BELL':        'Ketel Marte',
  'COBRA':              'Kevin Durant',
  'BLOCKHALE':          'Kevin McHale',
  'SLASH':              'Kordell Stewart',
  'BELL-CAMP':          'Kristian Campbell',
  'KING TUCK':          'Kyle Tucker',
  'WARP':               'Lamar Jackson',
  'TRIPLE THREAT':      'LaMelo Ball',
  'GRAND-MA-MA':        'Larry Johnson',
  'MARKSMAN':           'Lauri Markkanen',
  'LEBOSS':             'LeBron James',
  'SPRINKLER':          'Luis Arraez',
  'PANTERA':            'Luis Robert Jr.',
  'DONNY BUCKETS':      'Luka Dončić',
  'MAGIC':              'Magic Johnson',
  'EXTERMINABER':       'Malik Nabers',
  'MACHO':              'Manny Machado',
  'ALLENWRENCH':        'Marcus Allen',
  'MARVERATI':          'Marvin Harrison Jr.',
  'LINE-ART':           'Matt Leinart',
  'OLLIE':              'Matt Olson',
  'GOLDEN BULLET':      'Matthew Golden',
  'MEAN-JOE':           'Mean Joe Greene',
  'HOGE-BALL':          'Merril Hoge',
  'TIGRE':              'Miguel Cabrera',
  "MIC'D UP":           'Mike Evans',
  'WARGOD':             'Mike Trout',
  'GAMBLER':            'Mookie Betts',
  'MUGGSY':             'Muggsy Bogues',
  'JEESAW':             'Najee Harris',
  'LADY MAGIC':         'Nancy Lieberman',
  'HOMESTEAD':          'Nick Kurtz',
  'MUSTANG':            'Nikola Jokić',
  'AERONAUT':           'Nolan Arenado',
  'OZZMOSIS':           'Ozzie Albies',
  'WIZARD':             'Ozzie Smith',
  'PB BUCKETS':         'Paige Bueckers',
  'BANDELERO':          'Paolo Banchero',
  'MERLOMES':           'Patrick Mahomes',
  'SKEEE':              'Paul Skenes',
  'SNOWBEAR':           'Pete Alonso',
  'PEEK-A-BOO':         'Picabo Street',
  'PUKADOG':            'Puka Nacua',
  'SUPERBABY':          'Rafael Devers',
  'CHIEF':              'Robert Parish',
  'RODDER':             'Rod Smith',
  'STAR-BACH':          'Roger Staubach',
  'GLADIATOR':          'Roman Anthony',
  'MATATA':             'Ronald Acuña Jr.',
  'PORTALIZE':          'Sam LaPorta',
  'SAQUADS':            'Saquon Barkley',
  'BARNACLE':           'Scottie Barnes',
  'SHYSTEP':            'Shai Gilgeous-Alexander',
  'SWOOPES':            'Sheryl Swoopes',
  'SHOWTIME':           'Shohei Ohtani',
  '二百':               'Shohei Ohtani',
  '百三十':             'Shohei Ohtani',
  '百三十五':           'Shohei Ohtani',
  '百八十五':           'Shohei Ohtani',
  '百四十':             'Shohei Ohtani',
  'CROSBOW':            'Sidney Crosby',
  'HAYMAKER':           'Spencer Haywood',
  'TORQUE':             'Spencer Torkelson',
  'SPUDNICK':           'Spud Webb',
  'GRAVEDIGGER':        'Stefon Diggs',
  'MIDAS':              'Stephen Curry',
  'CASTLER':            'Stephon Castle',
  'STERLING':           'Sterling Sharpe',
  'SEA-LARGENT':        'Steve Largent',
  'YOUNG-GUNNER':       'Steve Young',
  'SKUBA':              'Tarik Skubal',
  'SCARY':              'Terry McLaurin',
  'THURMANATOR':        'Thurman Thomas',
  'TIMMY':              'Tim Brown',
  'HARD-DRIVE':         'Tim Hardaway',
  'WATTAGE':            'TJ Watt',
  'FROSTEBITE':         'Trae Young',
  'SWITCHBLADE':        'Travis Hunter',
  'YETI':               'Travis Kelce',
  'TURNTABLE':          'Trea Turner',
  'LAWMAN':             'Trevor Lawrence',
  'TONGUE-TWISTER':     'Tua Tagovailoa',
  'CHEETAH':            'Tyreek Hill',
  'HALIBURST':          'Tyrese Haliburton',
  'MAXED OUT':          'Tyrese Maxey',
  'GENERATOR':          'VJ Edgecombe',
  'VICTORY':            'Victor Wembanyama',
  'MAN OF STEAL':       'Vince Coleman',
  'INVINCEABLE':        'Vince Young',
  'VAMPIRE':            'Vladimir Guerrero Jr.',
  'CHICKEN MAN':        'Wade Boggs',
  'THRILL':             'Will Clark',
  'WILD BILL':          'William Contreras',
  'BANGFORD':           'Wyatt Langford',
  'X.L.':               'Xavier Legette',
  'XL':                 'Xavier Legette',
  'RISARCHER':          'Zaccharie Risacher',
  'LAVIATHAN':          'Zach LaVine',
  'BIG-Z':              'Zion Williamson',
};

/**
 * Look up the real athlete name for a given hero name.
 * Case-insensitive. Returns null if not found.
 * @param {string} heroName
 * @returns {string|null}
 */
function getAthleteForHero(heroName) {
  if (!heroName) return null;
  const key = String(heroName).toUpperCase().trim();
  return HERO_TO_ATHLETE[key] || null;
}

console.log(`✅ Heroes lookup loaded (${Object.keys(HERO_TO_ATHLETE).length} entries)`);
