// ============================================================
// ES Module — eBay search link builder + EPN affiliate tracking
//
// Affiliate params from BOBA-Scanner EPN account:
//   campid  : 5339143193  (Campaign: "default")
//   mkrid   : 711-53200-19255-0  (US rotation ID)
//   siteid  : 0  (eBay US)
//   toolid  : 10001
//   mkevt   : 1
//   mkcid   : 1
//
// Every eBay URL generated by this module automatically appends
// these params so affiliate commission is tracked on any resulting
// purchase.
// ============================================================

import { getCollections, getCurrentCollectionId, saveCollections } from '../../core/collection/collections.js';
import { showToast } from '../../ui/toast.js';
import { getApiToken } from '../../core/state.js';
import { recordPrice } from './price-trends.js';
import { getActiveAdapter } from '../../collections/registry.js';

const EBAY_AFFILIATE = {
  campid:  '5339143193',
  mkrid:   '711-53200-19255-0',
  siteid:  '0',
  toolid:  '10001',
  mkevt:   '1',
  mkcid:   '1'
};

const EBAY_SEARCH_BASE = 'https://www.ebay.com/sch/i.html';

// ── Build search query from card metadata ─────────────────────────────────────
// Delegates to the active adapter's buildEbayQuery() for collection-specific
// search terms (e.g. "bo jackson battle arena" for BOBA).

export function buildEbayQuery(card) {
  const adapter = getActiveAdapter();
  if (adapter) return adapter.buildEbayQuery(card);

  // Fallback for when no adapter is active
  return card.cardNumber || '';
}

// ── Append EPN affiliate params ───────────────────────────────────────────────
function appendAffiliateParams(url) {
  const separator = url.includes('?') ? '&' : '?';
  const params = new URLSearchParams(EBAY_AFFILIATE).toString();
  return `${url}${separator}${params}`;
}

// ── Build complete eBay search URL ────────────────────────────────────────────
export function buildEbaySearchUrl(card) {
  const query = buildEbayQuery(card);
  if (!query.trim()) return null;

  const searchUrl = `${EBAY_SEARCH_BASE}?_nkw=${encodeURIComponent(query)}&_sacat=0&LH_TitleDesc=0`;
  return appendAffiliateParams(searchUrl);
}

// ── Open eBay search in new tab ───────────────────────────────────────────────
export function openEbaySearch(cardIndex) {
  const collections = getCollections();
  const currentId   = getCurrentCollectionId();
  const collection  = collections.find(c => c.id === currentId);

  if (!collection?.cards[cardIndex]) {
    showToast('Card not found', '❌');
    return;
  }

  const card = collection.cards[cardIndex];
  const url  = buildEbaySearchUrl(card);

  if (!url) {
    showToast('Not enough card info to search eBay', '⚠️');
    return;
  }

  window.open(url, '_blank', 'noopener,noreferrer');
};

// ── Fetch average eBay market price for a card ────────────────────────────────
// Calls the ebay-browse serverless endpoint in keyword-search mode.
// Returns { avgPrice, lowPrice, highPrice, count } or null on failure.
export async function fetchEbayAvgPrice(card) {
  const query = buildEbayQuery(card);
  if (!query) return null;

  try {
    const apiToken = getApiToken();
    const headers  = { 'Content-Type': 'application/json' };
    if (apiToken) headers['X-Api-Token'] = apiToken;

    const res = await fetch('/api/ebay-browse', {
      method:  'POST',
      headers,
      body: JSON.stringify({
        query,
        cardNumber: card.cardNumber || '',
        hero:       card.hero       || '',
        athlete:    card.athlete    || ''
      })
    });

    if (!res.ok) return null;
    const data = await res.json();
    if (data.count === 0 || data.avgPrice === null) return { count: 0 };

    // Record price for trend tracking
    if (card.cardNumber && data.count > 0) {
      recordPrice(card.cardNumber, {
        avgPrice: data.avgPrice,
        lowPrice: data.lowPrice,
        highPrice: data.highPrice,
        count: data.count
      });
    }

    return data;
  } catch {
    return null;
  }
}
window.fetchEbayAvgPrice = fetchEbayAvgPrice;

// ── Build eBay SOLD listings search URL ──────────────────────────────────────
export function buildEbaySoldUrl(card) {
  const query = buildEbayQuery(card);
  if (!query.trim()) return null;

  const searchUrl = `${EBAY_SEARCH_BASE}?_nkw=${encodeURIComponent(query)}&_sacat=0&LH_Complete=1&LH_Sold=1&_sop=13`;
  return appendAffiliateParams(searchUrl);
}

// ── Fetch eBay sold/completed listing data for a card ────────────────────────
// Calls the ebay-sold serverless endpoint.
// Returns { lastSold: { price, date, title, url }, soldCount, avgSoldPrice, ... } or null.
export async function fetchEbaySoldData(card) {
  const query = buildEbayQuery(card);
  if (!query) return null;

  try {
    const apiToken = getApiToken();
    const headers  = { 'Content-Type': 'application/json' };
    if (apiToken) headers['X-Api-Token'] = apiToken;

    const res = await fetch('/api/ebay-sold', {
      method:  'POST',
      headers,
      body: JSON.stringify({
        query,
        cardNumber: card.cardNumber || '',
        hero:       card.hero       || '',
        athlete:    card.athlete    || ''
      })
    });

    if (!res.ok) return null;
    const data = await res.json();
    // Pass blocked flag through so UI can show a direct eBay link
    if (data.blocked) return { blocked: true, searchUrl: buildEbaySoldUrl(card) };
    if (!data.lastSold && data.soldCount === 0) return { soldCount: 0 };

    // Record sold price for trend tracking
    if (card.cardNumber && data.avgSoldPrice) {
      recordPrice(card.cardNumber, {
        soldAvg: data.avgSoldPrice,
        count: data.soldCount || 0
      });
    }

    return data;
  } catch {
    return null;
  }
}
window.fetchEbaySoldData = fetchEbaySoldData;

// ── Expose to window for HTML onclick handlers and lazy-loaded modules ────────
window.openEbaySearch     = openEbaySearch;
window.buildEbaySearchUrl = buildEbaySearchUrl;
window.buildEbaySoldUrl   = buildEbaySoldUrl;
window.buildEbayQuery     = buildEbayQuery;

console.log('✅ eBay module loaded');
