/// <reference types="@sveltejs/kit" />
/// <reference no-default-lib="true"/>
/// <reference lib="esnext" />
/// <reference lib="webworker" />

import { build, files, version } from '$service-worker';

const sw = self as unknown as ServiceWorkerGlobalScope;

const CACHE_NAME = `boba-scanner-${version}`;

// Assets generated by the build process (JS chunks, CSS)
const BUILD_ASSETS = build;

// Static files from the `static` directory
const STATIC_ASSETS = files;

// All assets to precache on install
const PRECACHE = [...BUILD_ASSETS, ...STATIC_ASSETS];

sw.addEventListener('install', (event) => {
	event.waitUntil(
		caches.open(CACHE_NAME).then((cache) => {
			return cache.addAll(PRECACHE);
		})
	);
	// Activate immediately — don't wait for old tabs to close
	sw.skipWaiting();
});

sw.addEventListener('activate', (event) => {
	event.waitUntil(
		caches.keys().then((keys) => {
			return Promise.all(
				keys
					.filter((key) => key !== CACHE_NAME)
					.map((key) => caches.delete(key))
			);
		})
	);
	// Take control of all open tabs immediately
	sw.clients.claim();
});

sw.addEventListener('fetch', (event) => {
	const url = new URL(event.request.url);

	// Skip non-GET requests (form submissions, API calls)
	if (event.request.method !== 'GET') return;

	// Skip API routes — these should always go to the network
	if (url.pathname.startsWith('/api/')) return;

	// Skip auth routes
	if (url.pathname.startsWith('/auth/')) return;

	// For navigation requests (HTML pages): network-first with cache fallback
	if (event.request.mode === 'navigate') {
		event.respondWith(
			(async () => {
				try {
					const response = await fetch(event.request);
					const clone = response.clone();
					caches.open(CACHE_NAME).then((cache) => cache.put(event.request, clone));
					return response;
				} catch (_err) {
					// Offline: serve from cache
					const cached = await caches.match(event.request);
					if (cached) return cached;
					const root = await caches.match('/');
					if (root) return root;
					return new Response(
						'<html><body><h1>BOBA Scanner is offline</h1><p>Please check your connection and try again.</p></body></html>',
						{ headers: { 'Content-Type': 'text/html' } }
					);
				}
			})()
		);
		return;
	}

	// For build assets (JS, CSS, fonts): cache-first (they're versioned by hash)
	if (PRECACHE.includes(url.pathname)) {
		event.respondWith(
			(async () => {
				const cached = await caches.match(event.request);
				if (cached) return cached;
				const response = await fetch(event.request);
				const clone = response.clone();
				caches.open(CACHE_NAME).then((cache) => cache.put(event.request, clone));
				return response;
			})()
		);
		return;
	}

	// For everything else: stale-while-revalidate
	event.respondWith(
		(async () => {
			const cached = await caches.match(event.request);
			const fetchPromise = fetch(event.request).then((response) => {
				const clone = response.clone();
				caches.open(CACHE_NAME).then((cache) => cache.put(event.request, clone));
				return response;
			}).catch(() => {
				return cached || new Response('', { status: 503 });
			});

			// Return cached immediately, update in background
			return cached || fetchPromise;
		})()
	);
});
