/// <reference types="@sveltejs/kit" />
/// <reference no-default-lib="true"/>
/// <reference lib="esnext" />
/// <reference lib="webworker" />

import { build, files, version } from '$service-worker';

const sw = self as unknown as ServiceWorkerGlobalScope;

// Phase 3: rebrand cache name to force a clean replacement on next deploy.
// Returning users pull fresh assets — stale BOBA-branded HTML/manifest
// would otherwise linger in the service worker cache for days.
const CACHE_NAME = `card-scanner-${version}`;

// Assets generated by the build process (JS chunks, CSS)
const BUILD_ASSETS = build;

// Static files from the `static` directory, excluding /vendor/ —
// opencv.js alone is ~11MB and is loaded on-demand by the scanner
// worker, so we don't want to ship it eagerly in install precache.
const STATIC_ASSETS = files.filter((f) => !f.startsWith('/vendor/'));

// All assets to precache on install
const PRECACHE = [...BUILD_ASSETS, ...STATIC_ASSETS];

sw.addEventListener('install', (event) => {
	event.waitUntil(
		caches.open(CACHE_NAME).then(async (cache) => {
			// Precache assets in parallel for faster installation.
			// Individual failures are non-fatal — assets will be fetched on demand.
			const results = await Promise.allSettled(
				PRECACHE.map(asset => cache.add(asset))
			);
			const failed = results.filter(r => r.status === 'rejected');
			if (failed.length > 0) {
				console.warn(`[sw] ${failed.length} assets failed to precache`);
			}
		})
	);
	// Activate immediately — don't wait for old tabs to close
	sw.skipWaiting();
});

sw.addEventListener('activate', (event) => {
	event.waitUntil(
		caches.keys().then((keys) => {
			return Promise.all(
				keys
					.filter((key) => key !== CACHE_NAME)
					.map((key) => caches.delete(key))
			);
		})
	);
	// Take control of all open tabs immediately
	sw.clients.claim();
});

sw.addEventListener('fetch', (event) => {
	const url = new URL(event.request.url);

	// Only handle http(s) requests — skip chrome-extension://, etc.
	if (url.protocol !== 'https:' && url.protocol !== 'http:') return;

	// Skip non-GET requests (form submissions, API calls)
	if (event.request.method !== 'GET') return;

	// Skip API routes — these should always go to the network
	if (url.pathname.startsWith('/api/')) return;

	// Skip auth routes
	if (url.pathname.startsWith('/auth/')) return;

	// Skip cross-origin requests — only cache our own origin
	if (url.origin !== sw.location.origin) return;

	// For navigation requests (HTML pages): network-first with cache fallback
	if (event.request.mode === 'navigate') {
		event.respondWith(
			(async () => {
				try {
					const response = await fetch(event.request);
					if (response.ok) {
						const clone = response.clone();
						caches.open(CACHE_NAME).then((cache) => cache.put(event.request, clone).catch((err) => console.warn('[sw] Cache put failed (navigate):', err)));
					}
					return response;
				} catch (_err) {
					// Offline: serve from cache
					const cached = await caches.match(event.request);
					if (cached) return cached;
					const root = await caches.match('/');
					if (root) return root;
					return new Response(
						'<html><body><h1>Card Scanner is offline</h1><p>Please check your connection and try again.</p></body></html>',
						{ headers: { 'Content-Type': 'text/html' } }
					);
				}
			})()
		);
		return;
	}

	// For build assets (JS, CSS, fonts): cache-first (they're versioned by hash)
	if (PRECACHE.includes(url.pathname)) {
		event.respondWith(
			(async () => {
				const cached = await caches.match(event.request);
				if (cached) return cached;
				const response = await fetch(event.request);
				if (response.ok) {
					const clone = response.clone();
					caches.open(CACHE_NAME).then((cache) => cache.put(event.request, clone).catch((err) => console.warn('[sw] Cache put failed (precache):', err)));
				}
				return response;
			})()
		);
		return;
	}

	// For version.json: always network-first so update checks get fresh data
	if (url.pathname === '/version.json') {
		event.respondWith(
			fetch(event.request).catch(() => caches.match(event.request).then(r => r || new Response('{}', { headers: { 'Content-Type': 'application/json' } })))
		);
		return;
	}

	// For everything else: stale-while-revalidate
	event.respondWith(
		(async () => {
			const cached = await caches.match(event.request);
			const fetchPromise = fetch(event.request).then((response) => {
				if (response.ok) {
					const clone = response.clone();
					caches.open(CACHE_NAME).then((cache) => cache.put(event.request, clone).catch((err) => console.warn('[sw] Cache put failed (swr):', err)));
				}
				return response;
			}).catch(() => {
				return cached || new Response('', { status: 503 });
			});

			// Return cached immediately, update in background
			return cached || fetchPromise;
		})()
	);
});

// Allow the client to trigger immediate activation of a new service worker
sw.addEventListener('message', (event) => {
	if (event.data?.type === 'SKIP_WAITING') {
		sw.skipWaiting();
	}
});
